//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcOkulEntities : DbContext
    {
        public DbMvcOkulEntities()
            : base("name=DbMvcOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDersler> tblDerslers { get; set; }
        public virtual DbSet<tblKulupler> tblKuluplers { get; set; }
        public virtual DbSet<tblNotlar> tblNotlars { get; set; }
        public virtual DbSet<tblOgrenciler> tblOgrencilers { get; set; }
        public virtual DbSet<tblCanliDersler> tblCanliDerslers { get; set; }
    }
}
