//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOgrenciler()
        {
            this.tblNotlars = new HashSet<tblNotlar>();
        }
    
        public int OGRENCIID { get; set; }
        public string OGRENCIAD { get; set; }
        public string OGRENCISOYADI { get; set; }
        public string OGRENCIFOTOGRAF { get; set; }
        public string OGRENCICINSIYET { get; set; }
        public Nullable<byte> OGRENCIKULUP { get; set; }
    
        public virtual tblKulupler tblKulupler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotlar> tblNotlars { get; set; }
    }
}
